# -*- coding: utf-8 -*-
"""Indian_Food_Analysisk.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kwuPhv5RwKdvNVPf02hIQa2S5w2ZPX2e
"""

# Commented out IPython magic to ensure Python compatibility.
# step -1) importing Require Libraries 
import pandas as pd
import numpy as np
import plotly.express as px
from plotly.offline import init_notebook_mode
import matplotlib.pyplot as plt
# %matplotlib inline
from wordcloud import WordCloud , ImageColorGenerator

# step-2) Import the data
data = pd.read_csv('/content/indian_food.csv')

data

data.head()

data.info()

data.describe()

data.columns

data.isnull().any()

data.isnull().sum()

data= data.replace(-1,np.nan)
data= data.replace(-1,np.nan)

data.head()

data.isnull().sum()

data.shape

#to find the which type of food most popular
pie_data = data.diet.value_counts().reset_index()

pie_data.columns = ['diet','count']
fig = px.pie(pie_data, values='count', names='diet', title='Proportion of Vegetarian and Non-Vegetarian dishes',
             color_discrete_sequence=['green', 'red'])
fig.show()

#to find which food is most eaten by customer
sweet_data = data[data['flavor_profile']=='sweet']
final_sweet_data = sweet_data[sweet_data['course']!='dessert']

final_sweet_data

flav_data = data.flavor_profile.value_counts().reset_index()
flav_data.columns = ['flavor_profile','prep_time']
fig =px.bar(flav_data,x='flavor_profile',y='prep_time',title='varity of item according to the flavor',color_discrete_sequence=['green'])
fig.show()

#to find which food take less time to prepare
cooking_time =data[['cook_time','name']]

cooking_time.head()

cooking_time=cooking_time.sort_values(['cook_time'],ascending=True)

ten_cook_quickly=cooking_time.head(10)

#cook_data.columns=['cook_time','name']
fig =px.bar(ten_cook_quickly,x='cook_time',y= 'name',title='dishes based on cooking time',color_discrete_sequence=['green'])
fig.show()

# to find which food take long time to prepare
data.columns

cooking_time_longest=cooking_time.sort_values(['cook_time'],ascending=False)
tencooking_time_longest=cooking_time_longest.head(10)

import matplotlib.pyplot as plt

y= tencooking_time_longest['cook_time']
x=tencooking_time_longest['name']
plt.plot(x,y)
plt.title('dishes based on cooking time')
plt.show()

